spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/dispatchdesk}
spring.datasource.username=${DB_USERNAME:dispatchdesk}
spring.datasource.password=${DB_PASSWORD:dispatchdesk}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

server.port=${SERVER_PORT:8080}

jwt.secret=${JWT_SECRET:9a6182bd79c2d6248b0a1d845f2e9bd6cd3de86d24f4178b568d99c6f63bc8835d09d6b14856423fa25baa2bded823e1d7364b27389dc8e7e31e577d4d88adcd}
jwt.expiration=${JWT_EXPIRATION:86400000}

cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173